If (!(Test-Path 'D:\Desktop\')){
echo "File does not exist, copying......"
cp "$HOME\Desktop\" D: -Recurse -Force
}
Else{
echo "File exist, removing......"
rm 'D:\Desktop\' -Recurse -Force
echo "Copying......"
cp "$HOME\Desktop\" D: -Recurse -Force
}
echo "Done!"

# SIG # Begin signature block
# MIIFiwYJKoZIhvcNAQcCoIIFfDCCBXgCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU1Z8INPnuUGFosfDs/Le77QnN
# 9f6gggMkMIIDIDCCAgygAwIBAgIQfhPhJr2jWpBOT9kW3WMNrzAJBgUrDgMCHQUA
# MBwxGjAYBgNVBAMTEUhMTVBvd2VyU2hlbGxDZXJ0MB4XDTE2MDYxOTAzMTcwM1oX
# DTM5MTIzMTIzNTk1OVowHDEaMBgGA1UEAxMRSExNUG93ZXJTaGVsbENlcnQwggEi
# MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCd2T6qlbisZAHJ1bk9CkDZgWDc
# ScALB7o7/Zz6gTrWaAMha2jNyOxY8brhMVMpps79CE0Iz/sgfIOvTSOAk0EHHtZn
# 4vQmAPLSuJmpaYN4JaCBUTRh16ojdDRly7x49FWyuOifkAloAKL9DTM+lfAfu7La
# nQBmDGUzfRUgNwzd5gdtyJKvbXTNJfdkIhboIRVFT0cUWLNDk7/sDyrSvjEIh72R
# hngN1U6GwgBIbLfuvzF3DPyHDMe/091mC/EhprKO2n8rx5/vQPaODxb4+OQM4Dow
# VrzjAGqJrhcI+ifShRXQT5DCQqx0v0bmCAi42gCYIh5LSJJRFxxYOdduvvkzAgMB
# AAGjZjBkMBMGA1UdJQQMMAoGCCsGAQUFBwMDME0GA1UdAQRGMESAECHHn0rHhc9g
# 55Nir8PVAAehHjAcMRowGAYDVQQDExFITE1Qb3dlclNoZWxsQ2VydIIQfhPhJr2j
# WpBOT9kW3WMNrzAJBgUrDgMCHQUAA4IBAQBGjg5kRESVoY3kL58o5XUENOwC5fpB
# xKmPMrgbYpKiD7bEHoUfkZ5ShBNvlktPpfu2Xn3eAVtVfQM4zOw3n0zUybrMGaaN
# Pe833xzupNtvnNic8/M/tV2lFBLb0CgV7Nfy3hc0VUsIaEcXjnGSJFjwuUfDM5m4
# xSiaTvFRF2Lw2HTZvLP4MF9L1dXz2eCT+0VoHi29jYhVVzH60HNMVIgBByR6y/nI
# asXDJt+9j5+jBqHkNEECKQguOzRrjNHCKYfuQ4IfVpzBA40gLrdjl3YZO5lztVY1
# tKsgVKo83pIVyth1dKwdpSmoeeAxQS95ZnVww0xGC2GkSVSvoDme8HP4MYIB0TCC
# Ac0CAQEwMDAcMRowGAYDVQQDExFITE1Qb3dlclNoZWxsQ2VydAIQfhPhJr2jWpBO
# T9kW3WMNrzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZ
# BgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYB
# BAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU88eWbsaI+07NSwcs3LAlvEni//swDQYJ
# KoZIhvcNAQEBBQAEggEAcRzs7v+2/h9tfdQF2EHUc3FY1UNy5840u9WgAWULSwD7
# KY4mSs808l4VZ58PDo6CcqEfnJ/8R8cvz9rZpuch+btNQJ8W51T64DLEr9Q4hUxw
# teSF/FYtJwg3QqHchlWrfyUJMVwQtyPQeE+3Jdtt2FuMNN/vHq8V6Z2D3UapyUCT
# jX/CWzTHm3fBKgAAqPB1IljHaZUZujSBZDk7YVx4a/WU9T7AMFwdFmOHr7idSNFn
# LzmKOul/onhbjdABFLeX5p1FhHL1bxKkBaU2h4hWMgsryIm7Vu/yOcZ01Aic/jiD
# D+62xXTRPhrhLVNKusWizD7w2g6OFUq1+Hlz6U0QMA==
# SIG # End signature block
