If (!(Test-Path 'D:\Desktop\')){
echo "File does not exist, copying......"
cp 'C:\Users\He Linming\Desktop\' D: -Recurse -Force
}
Else{
echo "File exist, removing......"
rm 'D:\Desktop\' -Recurse -Force
echo "Copying......"
cp 'C:\Users\He Linming\Desktop\' D: -Recurse -Force
}
echo "Done!"

# SIG # Begin signature block
# MIIFiwYJKoZIhvcNAQcCoIIFfDCCBXgCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUOCrn2P2YpoZ3u3watuuY4SHM
# 4cKgggMkMIIDIDCCAgygAwIBAgIQfhPhJr2jWpBOT9kW3WMNrzAJBgUrDgMCHQUA
# MBwxGjAYBgNVBAMTEUhMTVBvd2VyU2hlbGxDZXJ0MB4XDTE2MDYxOTAzMTcwM1oX
# DTM5MTIzMTIzNTk1OVowHDEaMBgGA1UEAxMRSExNUG93ZXJTaGVsbENlcnQwggEi
# MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCd2T6qlbisZAHJ1bk9CkDZgWDc
# ScALB7o7/Zz6gTrWaAMha2jNyOxY8brhMVMpps79CE0Iz/sgfIOvTSOAk0EHHtZn
# 4vQmAPLSuJmpaYN4JaCBUTRh16ojdDRly7x49FWyuOifkAloAKL9DTM+lfAfu7La
# nQBmDGUzfRUgNwzd5gdtyJKvbXTNJfdkIhboIRVFT0cUWLNDk7/sDyrSvjEIh72R
# hngN1U6GwgBIbLfuvzF3DPyHDMe/091mC/EhprKO2n8rx5/vQPaODxb4+OQM4Dow
# VrzjAGqJrhcI+ifShRXQT5DCQqx0v0bmCAi42gCYIh5LSJJRFxxYOdduvvkzAgMB
# AAGjZjBkMBMGA1UdJQQMMAoGCCsGAQUFBwMDME0GA1UdAQRGMESAECHHn0rHhc9g
# 55Nir8PVAAehHjAcMRowGAYDVQQDExFITE1Qb3dlclNoZWxsQ2VydIIQfhPhJr2j
# WpBOT9kW3WMNrzAJBgUrDgMCHQUAA4IBAQBGjg5kRESVoY3kL58o5XUENOwC5fpB
# xKmPMrgbYpKiD7bEHoUfkZ5ShBNvlktPpfu2Xn3eAVtVfQM4zOw3n0zUybrMGaaN
# Pe833xzupNtvnNic8/M/tV2lFBLb0CgV7Nfy3hc0VUsIaEcXjnGSJFjwuUfDM5m4
# xSiaTvFRF2Lw2HTZvLP4MF9L1dXz2eCT+0VoHi29jYhVVzH60HNMVIgBByR6y/nI
# asXDJt+9j5+jBqHkNEECKQguOzRrjNHCKYfuQ4IfVpzBA40gLrdjl3YZO5lztVY1
# tKsgVKo83pIVyth1dKwdpSmoeeAxQS95ZnVww0xGC2GkSVSvoDme8HP4MYIB0TCC
# Ac0CAQEwMDAcMRowGAYDVQQDExFITE1Qb3dlclNoZWxsQ2VydAIQfhPhJr2jWpBO
# T9kW3WMNrzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZ
# BgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYB
# BAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUjtAcGa5SyxiGTJ0fViPZfWmTEcAwDQYJ
# KoZIhvcNAQEBBQAEggEAGR0dFfEf6c7R0Tc+ArG2omYjL+bwulQetxKEs/LG1k86
# ztqwcpsVEqDOllxRH5fLrvQPDk+1fyKLT1w3Ig7NZwzbTvXHEn5e6lVRprTUk7Ip
# ubv9HYXmeooe6CqcyI2TcrO/0k9T0sELixQm5yvDvcWWxywwb5yQA4OeWFzTZ4Rf
# kuf9AcXjZXxQuhrno10Wf3l2yAbRF5IHFgK4kNjKayysfUNji99/oc+EtJsElaEs
# 8k1Ek9AYWFa9eCufXbspmfeHOtvOMkr3BISHSVLekXWPhfVuG7MtTUJ1dTsUyzpd
# 3j6O5BzS0ImY6phnL3wWG20XjyrAWyTItuIMmXIW/A==
# SIG # End signature block
